// @create-index

import { SMART_SKIN,
  TOGGLE_FIXED_HEADER,
  TOGGLE_FIXED_NAVIGATION,
  TOGGLE_FIXED_RIBBON,
  TOGGLE_FIXED_PAGE_FOOTER,
  TOGGLE_INSIDE_CONTAINER,
  TOGGLE_RTL,
  TOGGLE_MENU_ON_TOP,
  TOGGLE_COLORBLIND_FRIENDLY,
  TOGGLE_MENU_MINIFIED,
  TOGGLE_SHORTCUT,
  TOGGLE_COLLAPSE_MENU,
  FACTORY_RESET,
  onSmartSkin,
  onFixedHeader,
  onFixedNavigation,
  onFixedRibbon,
  onFixedPageFooter,
  onInsideContainer,
  onRtl,
  onMenuOnTop,
  onColorblindFriendly,
  toggleMenuMinified,
  onCollapseMenu,
  onToggleShortcut,
  handleBodyClasses,
  dumpLayoutToStorage,
  factoryReset } from './LayoutActions.js';
import layoutReducer from './layoutReducer.js';

export {SMART_SKIN,
  TOGGLE_FIXED_HEADER,
  TOGGLE_FIXED_NAVIGATION,
  TOGGLE_FIXED_RIBBON,
  TOGGLE_FIXED_PAGE_FOOTER,
  TOGGLE_INSIDE_CONTAINER,
  TOGGLE_RTL,
  TOGGLE_MENU_ON_TOP,
  TOGGLE_COLORBLIND_FRIENDLY,
  TOGGLE_MENU_MINIFIED,
  TOGGLE_SHORTCUT,
  TOGGLE_COLLAPSE_MENU,
  FACTORY_RESET,
  onSmartSkin,
  onFixedHeader,
  onFixedNavigation,
  onFixedRibbon,
  onFixedPageFooter,
  onInsideContainer,
  onRtl,
  onMenuOnTop,
  onColorblindFriendly,
  toggleMenuMinified,
  onCollapseMenu,
  onToggleShortcut,
  handleBodyClasses,
  dumpLayoutToStorage,
  factoryReset, layoutReducer}

  export * from './components'